[package]
edition = "2024"
name = "brioche"
version = "0.1.0"

[dependencies]
anyhow = { version = "1.0.100" }
burn = { version = "0.21.0-pre.4", features = [
  "std",
  "wgpu",
  "fusion",
  "record-item-custom-serde",
], default-features = false }
burn-store = { version = "0.21.0-pre.4" }
colorgrad = { version = "0.8.0", features = ["preset"] }
image = { version = "0.25.10" }
ndarray = { version = "0.17.2" }
ndarray-npy = { version = "0.10.0" }
ndarray-stats = { version = "0.7.0" }
ort = { version = "=2.0.0-rc.12", optional = true }

[dev-dependencies]
clap = { version = "4.5.56", features = ["derive"] }
rand = "0.9.2"
spinners = "4.2.0"

[features]
burn_onnx = ["dep:burn-onnx"]
cuda = ["burn/cuda"]
default = ["f32", "ort_onnx"]
f16 = ["ort/half"]
f32 = []
metal = ["burn/metal"]
ort_onnx = ["dep:ort"]
rocm = ["burn/rocm"]
wgpu = ["burn/wgpu"]

[[example]]
name = "sample_metal"
path = "examples/sample.rs"
required-features = ["metal"]

[[example]]
name = "sample_cuda"
path = "examples/sample.rs"
required-features = ["cuda"]

[profile.release-lto]
inherits = "release"
lto = true

[build-dependencies]
burn-onnx = { version = "0.21.0-pre.4", optional = true }
